"""
db/models.py
============
SQLAlchemy 2.0 ORM model definitions for StudyMate.

Tables
------
- threads    : A conversation context; groups messages and documents.
- documents  : A PDF uploaded by the student, linked to a thread.
- study_log  : An audit trail of study events.

Design notes
------------
- We use SQLAlchemy 2.0's `Mapped` / `mapped_column` API for full static-type
  safety and IDE auto-complete.
- All primary keys are string UUIDs (generated by the application layer, not
  the DB) so that IDs are portable if we ever migrate from SQLite → Postgres.
- `ondelete="CASCADE"` on FKs means deleting a thread automatically removes
  its documents and log entries at the DB level — important for cleanup.
"""

from datetime import datetime

from enum import Enum

from sqlalchemy import DateTime, Enum as SqlEnum, ForeignKey, Integer, String, func, Index

from app.config import DEFAULT_USER_ID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


# ---------------------------------------------------------------------------
# Declarative base — all models inherit from this single base class.
# ---------------------------------------------------------------------------

class Base(DeclarativeBase):
    """Shared declarative base for all StudyMate ORM models."""
    pass


# ---------------------------------------------------------------------------
# threads
# ---------------------------------------------------------------------------

class Thread(Base):
    """
    Represents a study session / conversation thread.

    A thread groups a set of uploaded documents and the chat history
    associated with them. Deleting a thread cascades to its documents
    and study-log rows.
    """

    __tablename__ = "threads"

    id: Mapped[str] = mapped_column(String, primary_key=True)
    """UUID string, generated by the application before insert."""

    title: Mapped[str] = mapped_column(String, nullable=False)
    """Human-readable label shown in the sidebar (e.g. 'CS101 Week 3')."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    """Timestamp set by the DB at INSERT time."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )
    """Timestamp of the latest persisted thread update."""

    # --- relationships (for ORM-level joins; not strictly required by CRUD) ---
    documents: Mapped[list["Document"]] = relationship(
        "Document", back_populates="thread", cascade="all, delete-orphan"
    )
    study_log: Mapped[list["StudyLog"]] = relationship(
        "StudyLog", back_populates="thread", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Thread id={self.id!r} title={self.title!r}>"


# ---------------------------------------------------------------------------
# documents
# ---------------------------------------------------------------------------

class Document(Base):
    """
    Represents a PDF (or other source document) uploaded by the student.

    Each document stores metadata about the file and the path to the FAISS
    vector index built from its chunks.  The vectorstore_path is used by the
    RAG retriever to load the correct index at query time.
    """

    __tablename__ = "documents"
    __table_args__ = (Index("ix_documents_thread_id", "thread_id"),)

    id: Mapped[str] = mapped_column(String, primary_key=True)
    """UUID string, generated by the application before insert."""

    thread_id: Mapped[str] = mapped_column(
        String, ForeignKey("threads.id", ondelete="CASCADE"), nullable=False
    )
    """Foreign key back to the owning thread."""

    filename: Mapped[str] = mapped_column(String, nullable=False)
    """Original filename as uploaded (e.g. 'lecture3.pdf')."""

    vectorstore_path: Mapped[str] = mapped_column(String, nullable=False)
    """
    Absolute (or workspace-relative) path to the directory containing the
    persisted FAISS index files (index.faiss + index.pkl).
    Convention: vectorstores/<thread_id>/<document_id>/
    """

    page_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    """Number of pages in the source PDF."""

    chunk_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    """Number of text chunks ingested into the vector store."""

    uploaded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    """Timestamp set by the DB at INSERT time."""

    # --- relationships ---
    thread: Mapped["Thread"] = relationship("Thread", back_populates="documents")
    def __repr__(self) -> str:
        return f"<Document id={self.id!r} filename={self.filename!r}>"


# ---------------------------------------------------------------------------
# study_log
# ---------------------------------------------------------------------------

class StudyLog(Base):
    """
    Append-only event log recording what the student studied in each thread.

    Every time the agent performs a meaningful action (answering a question,
    generating a quiz, etc.) we write one row here.  This powers future
    analytics dashboards and the RAGAS evaluation pipeline.
    """

    __tablename__ = "study_log"
    __table_args__ = (
        Index("ix_study_log_thread_id", "thread_id"),
        Index("ix_study_log_event_type", "event_type"),
    )

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    """Auto-incrementing integer PK — fine for a log table."""

    thread_id: Mapped[str] = mapped_column(
        String, ForeignKey("threads.id", ondelete="CASCADE"), nullable=False
    )

    document_id: Mapped[str | None] = mapped_column(
        String, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True
    )
    """
    Optional: which document triggered this event.
    NULL for events like web-search answers that don't originate from a
    specific uploaded document.
    """

    event_type: Mapped[str] = mapped_column(String, nullable=False)
    """
    Machine-readable event kind.  Allowed values (enforced at app layer):
      - "question_answered"
      - "quiz_generated"
      - "flashcards_generated"
      - "web_search_used"
    """

    topic: Mapped[str | None] = mapped_column(String, nullable=True)
    """
    Short human-readable description of what was studied, e.g.
    'Newton's laws of motion' or 'Chapter 4 review'.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )

    # --- relationships ---
    thread: Mapped["Thread"] = relationship("Thread", back_populates="study_log")

    def __repr__(self) -> str:
        return (
            f"<StudyLog id={self.id} thread={self.thread_id!r} "
            f"event={self.event_type!r}>"
        )


class TopicsCache(Base):
    """Cached extracted document topics; invalidated by a new document ID."""
    __tablename__ = "topics_cache"
    document_id: Mapped[str] = mapped_column(String, ForeignKey("documents.id", ondelete="CASCADE"), primary_key=True)
    topics_json: Mapped[str] = mapped_column(String, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())


class MemoryFactType(str, Enum):
    """Small, user-scoped memory categories; never stores raw transcripts."""

    WEAK_TOPIC = "weak_topic"
    STUDIED_TOPIC = "studied_topic"
    PREFERENCE = "preference"


class UserMemory(Base):
    """One compact, structured fact carried across otherwise separate threads."""

    __tablename__ = "user_memories"
    __table_args__ = (Index("ix_user_memories_user_created", "user_id", "created_at"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column(String, nullable=False, default=DEFAULT_USER_ID)
    fact_type: Mapped[MemoryFactType] = mapped_column(SqlEnum(MemoryFactType), nullable=False)
    topic: Mapped[str | None] = mapped_column(String, nullable=True)
    reason: Mapped[str] = mapped_column(String, nullable=False, default="quiz_score")
    detail: Mapped[str] = mapped_column(String, nullable=False)
    document_id: Mapped[str | None] = mapped_column(String, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, server_default=func.now())



class QuizAttempt(Base):
    """One factual, user-scoped record of a completed quiz attempt.

    Unlike :class:`UserMemory`, this table is an append-only activity record.
    It retains the document identifier even if the document is later deleted,
    so historical scores remain accurate.
    """

    __tablename__ = "quiz_attempts"
    __table_args__ = (Index("ix_quiz_attempts_user_created", "user_id", "created_at"),)

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[str] = mapped_column(String, nullable=False, default=DEFAULT_USER_ID)
    document_id: Mapped[str] = mapped_column(String, nullable=False)
    topic: Mapped[str] = mapped_column(String, nullable=False)
    correct_count: Mapped[int] = mapped_column(Integer, nullable=False)
    total_questions: Mapped[int] = mapped_column(Integer, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
